### ISSUE TITLE
social-instagram

### ISSUE THREAD

**Issue by hedii** [thesabbir/simple-line-icons#34] opened 2015-12-09 12:15 UTC
On google chrome 47.0.2526.73 (64-bit), osx 10.11.1, retina screen:

<img width="488" alt="capture d ecran 2015-12-09 a 13 12 19" src="https://cloud.githubusercontent.com/assets/5358048/11685083/b213b8a8-9e76-11e5-8b61-298d483904cb.png">

**Comment by praveenscience** [comment] 2016-04-25 13:12
Is this issue still persists?

**Comment by hedii** [comment] 2016-04-26 07:38
yes.
Chrome Version 50.0.2661.86 (64-bit)
OS X 10.11.4, retina screen
<img width="884" alt="capture d ecran 2016-04-26 a 09 36 49" src="https://cloud.githubusercontent.com/assets/5358048/14810310/928d31ec-0b92-11e6-991c-71046e9a3666.png">

**Comment by thesabbir** [comment] 2016-04-26 09:06
I could not understand. What's the issue here?

**Comment by hedii** [comment] 2016-04-26 09:07
don't you see blank parts on the icon?

**Comment by thesabbir** [comment] 2016-04-26 09:42
It's by design

**Comment by hedii** [comment] 2016-04-26 09:48
i don't think so. i already had this kind of issue when creating svg icons. anyway cool library!

**Comment by ahmadfiroz** [comment] 2016-04-26 10:33
There might be a problem with the retina screen. It should look like this. Not sure why. 
![ss 2016-04-26 at 04 29 37](https://cloud.githubusercontent.com/assets/3663724/14815325/89662530-0bcc-11e6-93d2-41bc9deba13d.png)

**Comment by hedii** [comment] 2016-04-26 10:36
@ahmadfiroz yes. and the instagram icon is the only one that looks bad on retina

**Comment by thesabbir** [comment] 2016-04-26 22:28
haha I have a retina too 🍭 so I was used to the bad icon

**Comment by thesabbir** [comment] 2016-05-03 17:02
@hedii fixed in 2.3.0. Thanks to @mruz .

**Closed by thesabbir** 2016-05-03 17:02 UTC
Labels: bug, help wanted
